aws-region = "us-east-1"
vpc-cidr = "10.0.0.0/16"
vpc-name = "Terraform"
aws-availability-zones = "us-east-1b,us-east-1c"
jenkins-ami-id = "ami-c58c1dd3"
jenkins-instance-type = "t2.nano"
jenkins-key-name = "terraform"
